### ISSUE TITLE
ios undefine analyticsconnector class from amplitude

### ISSUE THREAD

**Issue by AkiraJue** [amplitude/unity-plugin#104]
build ios platform error.

**Comment by bohan-amplitude** [comment]
Hi @AkiraJue , Thanks for provide feedback. Could you provide more details about the error like error logs and how to reproduce?

**Comment by mathieudel** [comment]
Hi !

I think I got the same issue.
Here is the relevant logs:

`8952: ❌;  Undefined symbols for architecture arm64
8953: > Symbol: _OBJC_CLASS_$_AnalyticsConnector
8954: > Referenced from: objc-class-ref in Amplitude.o
8955: ❌;  ld: symbol(s) not found for architecture arm64
8956: ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
8957: ** ARCHIVE FAILED **
8958: The following build commands failed:
8959: 	Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-ejfmyrsekvocjxffwlzilmiivtkh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
8960: (1 failure)
8961: Exit status: 65`

**Comment by DimaPetrinko** [comment]
Hello
Having the exact same error during unity ios build using jenkins

**Comment by BlackstaffGames** [comment]
Hey, 

Having the same issue as above for iOS. Using Unity 2019.4 and Xcode 13.3 and version 2.5.0 of the SDK.

Will try 2.4 version in the meantime as suggested above.

**Comment by arda-arvis** [comment]
Hello!
We are having the same error.
GitLab CI/CD pipeline runner, Mac Mini M1 2020, Unity 2020.3.20f1.

**Comment by dnshi** [comment]
A new release of the Unity plugin is ready. Please install the new version to resolve the issue. Thanks.

**Comment by ugurinal** [comment]
The problem still occurs on Unity 2021.3.6f1. Using v2.4.0 solved the issue. @dnshi

**Comment by dnshi** [comment]
> The problem still occurs on Unity 2021.3.6f1. Using v2.4.0 solved the issue for me. @dnshi

@ugurinal Thanks for the report. Could you please share me which unity plugin version has the issue? Is the problem reproduced on v2.5.1?

**Comment by ugurinal** [comment]
@dnshi Yes, it is reproduced on v2.5.1.

**Comment by dnshi** [comment]
@ugurinal Could you please share your error message and your podfile?

**Comment by ugurinal** [comment]
@dnshi 


Undefined symbol: _OBJC_CLASS_$_AnalyticsConnector

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AnalyticsConnector", referenced from:
      objc-class-ref in Amplitude.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Pod file:
```
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Amplitude', '~> 8.10.0'
  pod 'FBSDKCoreKit', '~> 14.0'
  pod 'FBSDKCoreKit_Basics', '~> 14.0'
  pod 'FBSDKGamingServicesKit', '~> 14.0'
  pod 'FBSDKLoginKit', '~> 14.0'
  pod 'FBSDKShareKit', '~> 14.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
use_frameworks!
```

**Comment by dnshi** [comment]
@ugurinal Do you remove any existing iOS plugin source files before importing the new version? For the version 2.5.1, most of iOS files from Unity side are removed and imported from from Pod file `pod 'Amplitude', '~> 8.10.0'`. From the error message, it looks like that some Unity iOS plugin files stay in your dev environment.
