### ISSUE TITLE
How to set user groups with SDK

### ISSUE THREAD

**Issue by kbunarjo** [amplitude/unity-plugin#110]
## Summary
I've added the SDK through the Unity SDK package manager, but I'm unable to set the user group. The [documentation](https://www.docs.developers.amplitude.com/data/sdks/unity/#set-user-groups) says i can call `setGroup` on the instance of `Amplitude`, but my editor says it doesn't exist. I also checked the `Amplitude.cs` source code and couldn't find anything about groups there.

Specifically, this line of code from the documentation example doesn't actually work:

```
Amplitude.getInstance().setGroup("orgId", "15");
```

**Comment by kbunarjo** [comment]
Hi, any update here this is pretty critical for us to use any amplitude events in our game.

**Comment by qingzhuozhen** [comment]
Hi @kbunarjo, sorry for the late reply and doc confusion earlier. We are working to add support for that method in https://github.com/amplitude/unity-plugin/pull/114

**Comment by kbunarjo** [comment]
Closing this issue cause it's fixed with the [latest release](https://github.com/amplitude/unity-plugin/releases/tag/v2.6.0).

Thanks @qingzhuozhen !
