### ISSUE TITLE
Assembly Definition files are missing

### ISSUE THREAD

**Issue by halfgrey** [amplitude/unity-plugin#116]
## Expected Behavior
When Unity developers use assembly definition files they should be able to add a reference to the Amplitude assembly definition files so that they can use the SDK. For example AmplitudeSDKCore.asmdef

## Current Behavior
The assembly definition files are missing since they are filtered by the .gitignore file. Only the .meta files are still existing.

## Possible Solution
Remove asmdef filter from .gitignore and commit asmdef files again so that developers can reference and use the SDK code. 

## Steps to Reproduce
1. Create a new empty Unity Project with an example script.
2. Create an assembly definition file next to that script and name it whatever you like. For example. com.Company.Example
3. Import Amplitude via Package Manager and the git url
4. Try to use amplitude in your script (ERROR: You won't be able to use the amplitude c# code as you would need to reference for example AmplitudeSDKCore.asmdef to com.Company.Example.

## Environment
- Amplitude SDK Version: 2.6.0
- Device: Unity Editor 2021.3.1f1

**Comment by shamruk** [comment]
Had to create asmdef myself. Took me about 1 minute, but should be there in the 1st place

**Comment by justin-fiedler** [comment]
Hi @shamruk thanks for the heads up on this. Glad you found a workaround. We have this in our backlog but do not have an ETA for the fix.

**Comment by lordmortis** [comment]
This is _still broken_

**Comment by izaaz** [comment]
This should be fixed in version 2.8.0. @lordmortis - can you please confirm where you're seeing this?

If you're using the unitypackage file, you can find all the different versions here:
https://github.com/amplitude/unity-plugin/releases/tag/v2.8

For direct loading from UPM, you can use the following branch
main, [main-without-edm-and-dependency](https://github.com/amplitude/unity-plugin/tree/main-without-edm-and-dependency) or [main-without-edm](https://github.com/amplitude/unity-plugin/tree/main-without-edm)

Can you please confirm if you're seeing an issue with these branches as well?

**Comment by lordmortis** [comment]
Looking at the main branch on GitHub, I can see the assembly definitions 
are 
[back](https://github.com/amplitude/unity-plugin/blob/main/Assets/Amplitude/AmplitudeSDKCore.asmdef)

However I’m not sure using the main branch is ideal as if a new 
version is marked main it is likely that unity will upgrade the package 
next time it refreshes (as it will use the branch/tag) - so to make the 
time-frame more controllable for us, we really need the tags.

2.7.0 and 2.6.0 both have corresponding `-no-edm-and-dep` and `-no-edm` 
tags (but those versions are missing the assembly references)

Do you know what Unity’s behaviour is when the tag/branch specified in 
the manifest updates in git? Will it just auto-update?

I can just use `33720007dc6dd7a1d0a3f41292554ea504894524` as that’s 
the `main-without-edm-and-dependency` for 2.8.0 - but it’s definitely 
less than ideal.

**Comment by lordmortis** [comment]
Can confirm that using `33720007dc6dd7a1d0a3f41292554ea504894524` at least compiles in unity (though the asset definition changed from the version we were on). I haven't built this just yet, but this is further that I was getting before.

**Comment by izaaz** [comment]
Using the hash isn't the cleanest thing to do. I've added two new tags 

`v2.8.0-no-edm-and-dep` and `v2.8.0-no-edm`

**Comment by lordmortis** [comment]
Thank you! Hopefully that will make it clearer for others!
