### ISSUE TITLE
Unity iOS xcode 'Amplitude\Amplitude.h' file not found

### ISSUE THREAD

**Issue by Brian-McElroy** [amplitude/unity-plugin#118]
I added Amplitude to an existing Unity project, on Android it was fine, but on iOS when I try to build I get this error ... "'Amplitude\Amplitude.h' file not found"

Project uses Unity 2021.3.9f1 and Ar foundation 

I get the same issue with a brand new Unity 2021.3.9f1 project, with nothing in it but the Amplitude SDK. I used the 2.6.0 amplitude-unity.unitypackage file from here https://github.com/amplitude/unity-plugin/releases

![image](https://user-images.githubusercontent.com/2582934/199322152-5eeb403f-d838-4c11-9eaf-14977046e280.png)

**Comment by qingzhuozhen** [comment]
Hi @Brian-McElroy, thanks for choosing Amplitude. Would you mind sharing how you install the SDK? In recent versions, we updated to use the DependencyManager to resolve the iOS dependency. There are tags including the DependencyManager or not.

**Comment by Brian-McElroy** [comment]
@qingzhuozhen yeah I updated my original comment saying how I installed the smaller unitypackage on a blank project.. I am now trying the bigger unitypackage with the dependency manager thing, and clicking on install cocoapods option before building.. I am having more errors though. 

"
'/Users/bm/Library/Developer/Xcode/DerivedData/Unity-iPhone-ashdibvxumgdwsahvbmbnujwnvks/Build/Products/ReleaseForRunning-iphoneos/Amplitude/Amplitude.framework/Amplitude(AMPDeviceInfo.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/bm/Library/Developer/Xcode/DerivedData/Unity-iPhone-ashdibvxumgdwsahvbmbnujwnvks/Build/Products/ReleaseForRunning-iphoneos/Amplitude/Amplitude.framework/Amplitude' for architecture arm64
"

![image](https://user-images.githubusercontent.com/2582934/199342046-108398a5-a972-4f46-b15b-e83e010c53d2.png)

**Comment by JonLandmark** [comment]
I am also getting the same bitcode error seen above. Sounds like it requires amplitude to rebuild with ENABLE_BITCODE. Annoyingly without this, I'm having to disable bitcode for my whole project. Can this be looked into?

There is an old issue on the ios SDK which sounds like it shares some similarities - https://github.com/amplitude/Amplitude-iOS/issues/384

**Comment by DiegoDePalacio** [comment]
I created an empty Unity 2021.3.17f1 project, added Amplitude SDK, and create an Xcode project by building for iOS in the Unity Editor.

Trying to Archive gives me that exact error.

Is there any workaround to create an iOS build with the latest Unity's Amplitude SDK?

**Comment by DiegoDePalacio** [comment]
I found the solution.

In Unity is necessary to choose from the menu:
Assets > External Dependency Manager > iOS Resolver > Settings

On the settings is necessary to change the "Cocoapods Integration" from
Xcode Workspace - Add Cocoapods to the Xcode workspace, to be instead
Xcode Project - Add Cocoapods to the Xcode project

In Xcode is necessary to choose the "Project", then "Build Settings" and in the "Build Options" is necessary to set "Enable Bitcode" to "No"

Then "Archive" can be completed successfully, at least in my case 😅

**Comment by xk0fe** [comment]
I've managed to solve this issue without turning off bitcode in Xcode project

In Unity:
1) Assets -> External Dependency Manager -> iOS Resolver -> Settings
2) Set "Cocoapods Integration" to - Xcode Project
3) Uncheck "Use Shell to Execute Cocoapod Tool"
