### ISSUE TITLE
Change plugin post processing stack to C#

### ISSUE THREAD

**Issue by cmlewis89** [amplitude/unity-plugin#12]
Why not use Unity's built in methods to add the dependencies you need?

	//GET PBX PROJ
	string projPath = Path.Combine(path, "Unity-iPhone.xcodeproj/project.pbxproj");
	PBXProject project = new PBXProject();
	project.ReadFromFile(projPath);
	string xcodeTarget = project.TargetGuidByName("Unity-iPhone");

	//Amplitude -- enable OBJC exceptions
	project.AddBuildProperty(xcodeTarget, "GCC_ENABLE_OBJC_EXCEPTIONS", "YES");

Here is a more complete example:
https://github.com/adjust/unity_sdk/blob/master/Assets/Editor/AdjustEditor.cs

**Comment by haoliu-amp** [comment]
@cmlewis89 Is this for iOS only?

**Comment by EtienneMarbotic** [comment]
@haoliu-amp Yes, it is iOS only. Currently, we're forced to do it on a script on our side that is packaged with your plugin (or, worst case, do it manually before every builds).

There is also another thing we need to add (using the script I mentioned, or manually), written in your documentation: 
<img width="717" alt="Capture d’écran 2020-03-03 à 12 22 06" src="https://user-images.githubusercontent.com/39184965/75771178-bc37f100-5d49-11ea-8aba-f9f8805eb917.png">

Here is our internal code we use if you want to package it with your plugin ;)
![Capture d’écran 2020-03-03 à 12 24 23](https://user-images.githubusercontent.com/39184965/75771299-fdc89c00-5d49-11ea-947f-dcda81215c60.png)

**Comment by haoliu-amp** [comment]
@EtienneMarbotic Thanks for your feedback. We will add this to our backlog.

**Comment by EtienneMarbotic** [comment]
Do you want me to add this via pull-request also ? Or maybe you prefer to take a look at it in intern ?

**Comment by haoliu-amp** [comment]
Thank you! A PR will be great, I will review it tmr. Look like this is a post processing build script, right?

**Comment by EtienneMarbotic** [comment]
Ok I'll do it, and yes it is

**Comment by EtienneMarbotic** [comment]
PR ready to review (and there is also another one waiting about array logs ;) )

**Comment by haoliu-amp** [comment]
Yep, I left comments to both PRs, could you take a look?
