### ISSUE TITLE
Dependencies in amplitude-unity-2.13.3

### ISSUE THREAD

**Issue by Bryksin** [amplitude/unity-plugin#13]
Hi
As far as I see you have dependencies for `okhttp` and `okio` inbuild in your jar

First of all, it is outdated and create serious problems in dependency convergence with Twitter plugin for Unity which also happens to uses them

Also, it is inbuilt inside the jar, where Twitter just add separate jar libraries which are easy to delete or maintain. could you please update your plugin?

**Comment by aheliver** [comment]
Seriously, not fixed yet?!? 
Dear Amplitude, you are a great service, but this dependencies inside makes a lot of pain!

**Comment by alex-turantsev** [comment]
any fixes??

**Comment by maxshayne** [comment]
Still nothing?
We have duplicate conflicts for `okhttp` with amplitude-unity-2.20.0 and vungle-adapter

**Comment by haoliu-amp** [comment]
Hello, we (Amplitude) will bump this priority and fix it ASAP.

**Comment by VictorPapiyGen** [comment]
Having same issue with vungle-adapter as @maxshayne . @haoliu-amp is it already fixed?

**Comment by haoliu-amp** [comment]
Hello everyone, we're truly sorry about the delay. As we promised, we are increasing our support for our SDKs. 

And here you go, dependencies issue should be gone now. Please spend some time to take a look at the CHANGELOG and also our updated README.
https://github.com/amplitude/unity-plugin/blob/master/CHANGELOG.md

Thanks!!
