### ISSUE TITLE
Does Amplitude realize that the point of the dependency manager is, that it handles dependencies?

### ISSUE THREAD

**Issue by VinceChimp** [amplitude/unity-plugin#133]
## Summary
The EDM is intended to pull in external dependencies, meaning all .aar and .jar files can be pulled from Maven repositories and automatically resolved based on a simple android manifest file for example. Meaning you do not have to hard include the files, upgrading is easily resolved automatically, and you do not get conflicting includes for packages that need the exact same prerequisite parts.

Why are we doing this the old fashioned way in 2024? GameAnalytics has this figured out for a long while.

**Comment by izaaz** [comment]
@VinceChimp - thank you for reaching out. We release three versions of the SDK for this very reason.

https://github.com/amplitude/unity-plugin/releases/tag/v2.8

From what I read, you need this package? `amplitude-unity-no-edm-and-dep.unitypackage`

If there's anything else we should be doing to make this easier on y'all, please let me know. Happy to help. (I know we should document this somewhere so its not hidden in the releases, so i'll take an action item for that)

**Comment by VinceChimp** [comment]
That seems to be the case.

I think from a Unity developer's perspective, and a compatibility perspective, this should be the recommended route and the default.
Just the minimal code, and a package manager include that automatically resolves all dependencies.
It is what all other big parties recommend for their plugins too.
Thanks for the help!
