### ISSUE TITLE
Amplitude init causing crash in Unity 2018.2

### ISSUE THREAD

**Issue by MiketoString** [amplitude/unity-plugin#16]
After upgrading our project to Unity 2018.2 (latest stable), we noticed a crash was traced back to Amplitude.Instance.init -- removing calls to Amplitude resolved the error.

Think it has something to do with how the plugin is communicating with the native java code via CallStatic.  Included the crash log below:

```
java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
Build fingerprint: 'google/walleye/walleye:8.0.0/OPD3.170816.012/4343094:user/release-keys'
Revision: 'MP1'
pid: 4764, tid: 4859, name: UnityMain  >>> com.xyz.com <<<
    r0 00000000  r1 00000000  r2 4b3e9c59  r3 00000000
    r4 d527e148  r5 00000000  r6 00002a36  r7 f1c7b7ed
    r8 c4dde810  r9 ec64f7c4  sl e7828810  fp d527e198
    ip d6991c88  sp d527e0c8  lr d5533cc0  pc f4a626cc  cpsr f2151d10
	at libc.strlen(strlen:71)
	at libunity.AndroidJNIBindingsHelpers::CallStaticStringMethod(void*, void*, dynamic_array<jvalue, 0u> const&)(CallStaticStringMethod:292)
	at libunity.AndroidJNI_CUSTOM_CallStaticStringMethod(void*, void*, Il2CppArray*)(AndroidJNI_CUSTOM_CallStaticStringMethod:124)
	at libil2cpp.0089013c(Native Method)
```

**Comment by djih** [comment]
Thanks for reporting @MiketoString ! Unfortunately the unity plugin has not been updated to support the latest version of Unity yet

**Comment by MiketoString** [comment]
Hi @djih, noticed a recent commit that references 2018.2:
https://github.com/amplitude/unity-plugin/commit/78813af38e7d33b5acda5e21aa7ec365666287c6

Is Unity 2018 supported now or still in the works?

**Comment by djih** [comment]
@MiketoString Unity 2018 is now supported. I verified that our demo app works in Unity 2018 and builds into iOS and Android apps
