### ISSUE TITLE
okhttp duplicate library issue

### ISSUE THREAD

**Issue by NoahHahm** [amplitude/unity-plugin#25]
we use the okhttp library as a separate aar, jar in unity.
duplicate problem with the amplitude unity library.
change the reference to the okhttp library.

**Comment by haoliu-amp** [comment]
<img width="621" alt="Screen Shot 2020-02-11 at 12 10 55 AM" src="https://user-images.githubusercontent.com/57638692/74551989-20b11e80-4f09-11ea-92c7-ef7f38c7738d.png">
Did you uncheck all the okhttp related libraries while importing our package?
