### ISSUE TITLE
Removing after 

### ISSUE THREAD

**Issue by pashara** [amplitude/unity-plugin#27]
Hi!
Im trying to build android project. "Play Services Resolver" force resolve before build. As result,
com.amplitude.android-sdk-2.24.1.aar and all *.jar files (from amplitude package) was removed from project. So, I have error
`AndroidJavaException: java.lang.ClassNotFoundException: com.amplitude.unity.plugins.AmplitudePlugin
    java.lang.ClassNotFoundException: com.amplitude.unity.plugins.AmplitudePlugin`
What could be the problem?
P.S. Additional SDKs in project
1. Appsflyer
2. Firebase (Analytics)
3. Facebook
4. Amplitude

**Comment by haoliu-amp** [comment]
Are you using `Play Services Resolver` yourself? It's not needed to import our plugin, you need to double click the package file and choose the library and files you need.

**Comment by pashara** [comment]
Hi!
Other SDK's require the use of `force resolve`.
So, for example, `AdMob` inside `MoPub` (forgot to specify in sdk's), `Facebook` & `Firebase` may require using `Force resolve functions (or not?).
I do not use `Play Services Resolver` for import `Amplitude`. The fact is that the `Play Services Resolver` deletes the amplitude files from the project when a dependency check occurs.

**Comment by haoliu-amp** [comment]
Hi I think this issue you probably should check with https://github.com/googlesamples/unity-jar-resolver to see why it got removed.

**Comment by haoliu-amp** [comment]
I'm going to close this for now. Feel free to reopen it.

**Comment by pashara** [comment]
Helps to create file `AmplitudeDependencies.xml` in `Amplitude/Editor` with content
`<dependencies>
 <androidPackages>
   <androidPackage spec="com.amplitude:android-sdk:2.24.1"/>
 </androidPackages>
</dependencies>`
Resolver put `
<package>com.amplitude:android-sdk:2.24.1</package>
....
<file>Assets/Plugins/Android/com.amplitude.android-sdk-2.24.1.aar</file>` 
in `/ProjectSettings/AndroidResolverDependencies.xml` and now Resolver does not delete `com.amplitude.android-sdk-2.24.1.aar` file.

**Comment by haoliu-amp** [comment]
You DON'T need to add AmplitudeDependencies.xml to your project.
