### ISSUE TITLE
Array logs detailed

### ISSUE THREAD

**Issue by EtienneMarbotic** [amplitude/unity-plugin#28]
Hi,

for the first time, I used `setUserProperty` with an array and I found out that your `Log` method is useless with arrays (it only prints the array type).
I fixed all the array logs to display the content of the array:
`Log ($"C# setUserProperty {property} {string.Join(", ", array)}");`
You can also add a log method that accepts an array directly instead of editing all `Log` lines ^^

Hope you'll have time to add this really quick fix on your next update :p

Thanks for your work by the way :)

**Comment by haoliu-amp** [comment]
@EtienneMarbotic Thanks for your message! Actually if you don't mind you can even submit a PR against our repo.

**Comment by EtienneMarbotic** [comment]
I've never done this but I'm gonna try if I have time :)

**Comment by EtienneMarbotic** [comment]
Done :)
