### ISSUE TITLE
Submitting event just before leaving app

### ISSUE THREAD

**Issue by mgrider** [amplitude/unity-plugin#3]
I am working on an application published to both iOS and Android. We are tracking "exit" events, and the code (roughly) looks like this:

```
		Dictionary<string, object> eventOptions = new Dictionary<string, object>() {
			{"screenName" , pageName },
			{"tapElement" , tappedElement }
		};
		Amplitude.Instance.logEvent(EVENT_TYPE_TAPPED, eventOptions);
		Application.OpenURL(URL);
```

The strange thing is that the events are reported correctly on Android, but not on iOS.

My first thought is that it's probably a timing and/or caching `logEvent`s issue, (where essentially the app stops running before the events hit the network, but in Android, presumably the app is still running in the background). I looked for a `flush` or equivalent method, but didn't see one. Does that sound like the likely culprit to whoever is reading this?

**Comment by djih** [comment]
That does sound correct, there is a slight discrepancy between how our 2 SDKs handle going into the background:

In iOS, the enterBackground method will attempt to upload all remaining events: https://github.com/amplitude/Amplitude-iOS/blob/master/Amplitude/Amplitude.m#L1006

In Android, the exitForeground method does not flush: https://github.com/amplitude/Amplitude-Android/blob/master/src/com/amplitude/api/AmplitudeClient.java#L592, so I would expect some events left unsent (they would still get sent when the user reopens the app).

Wait that sounds like the reverse of what you are seeing, can you confirm?

**Comment by mgrider** [comment]
That is indeed the opposite of what we've had reported. I haven't seen it myself though. I'll try to confirm with our analytics folks.

**Comment by mgrider** [comment]
(I did confirm that is what they are seeing.)

**Comment by djih** [comment]
@mgrider  you confirmed that iOS does not flush? Your exit event if it's not sent will be added to a queue. When the user opens the app the next time, any queued events will be flushed.

**Comment by djih** [comment]
@mgrider we recently added flushing of events on app minimize/close on our Android SDK (v2.9.0). We also just updated our unity plugin to include the latest version of the Android SDK (v2.9.2)
