### ISSUE TITLE
aar getting deleted while Force resolve in Unity jar resolver.

### ISSUE THREAD

**Issue by Javasamurai** [amplitude/unity-plugin#31]

**Comment by haoliu-amp** [comment]
Hello, 

Do you use unity jar resolver yourself? If yes, you will have 3 choices.
1. Manually add those deleted jars back.
2. Add the jars of Amplitude SDK and the ones it depends on into your XXXDependencies.xml.
3. Check if unity jar provides a way for you to exclude jars which it shouldn't touch.

**Comment by pashara** [comment]
Javasamurai, try https://github.com/amplitude/unity-plugin/issues/27

**Comment by haoliu-amp** [comment]
@pashara Sorry about getting back and forth. As I mentioned in #27 , I wonder what's the motivation for you to include `AmplitudeDependencies.xml` in your project. That file is NOT needed.

**Comment by haoliu-amp** [comment]
Pls take a look at the README file. I just updated it with how to work around with this issue.

**Comment by Javasamurai** [comment]
Yes. Adding the Dependencies solved the issue.

**Comment by ArwaAlrazooq** [comment]
@haoliu-amp I'm also facing the same problem, but I can't locate the *Dependency.xml to add the dependencies.

**Comment by haoliu-amp** [comment]
Please take a look at the README file. If you are not using google resolver, then you won't have the xxxDependency.xml file.

**Comment by ArwaAlrazooq** [comment]
Yes, I'm using the google resolver and followed the instructions in README file but I didn't find the *Dependency.xml file. Is it inside Amplitude folder? or located in another folder ?

**Comment by haoliu-amp** [comment]
@ArwaAlrazooq If you are using that yourself, it should be in your project folder. Not from Amplitude.
