### ISSUE TITLE
Setting custom session data to session start and session end

### ISSUE THREAD

**Issue by Javasamurai** [amplitude/unity-plugin#34]
Is there a way to set custom parameters to **[Amplitude]** **StartSession** and **EndSession** Events?

**Comment by haoliu-amp** [comment]
No, what kind custom params you wanna pass in?

**Comment by Javasamurai** [comment]
Timestamp, sessionCount since first launch. TimeSpent within session end.

**Comment by haoliu-amp** [comment]
If you are tracking those themselves you can just log them as event properties on your own event.
And disable automatic session events.
