### ISSUE TITLE
Unity 2019.3 PostProcess issue

### ISSUE THREAD

**Issue by mystikxkemix** [amplitude/unity-plugin#37]
Hi,

On Unity 2019.3, all the frameworks are linked to the new target `UnityFramework`.
However, your PostProcess script change flags for `Unity-iPhone` target.

You need to change this line:
```var targetGuid = proj.TargetGuidByName(PBXProject.GetUnityTargetName());```
by those:
```
#if UNITY_2019_3_OR_NEWER
      var targetGuid = proj.TargetGuidByName(proj.GetUnityFrameworkTargetGuid());
#else
      var targetGuid = proj.TargetGuidByName(PBXProject.GetUnityTargetName());
#endif
```

Hope you will fix this soon 🙃

**Comment by Ilya-d** [comment]
Unity 2019.3.11f does not compile latest version. GetUnityTargetName is deprecated.

**Comment by haoliu-amp** [comment]
@mystikxkemix @Ilya-d  Thank you! Actually the change should be 
```
#if UNITY_2019_3_OR_NEWER
      var targetGuid = proj.GetUnityFrameworkTargetGuid();
#else
      var targetGuid = proj.TargetGuidByName(PBXProject.GetUnityTargetName());
#endif
```

**Comment by haoliu-amp** [comment]
https://github.com/amplitude/unity-plugin/releases/tag/v1.2.0
