### ISSUE TITLE
Google External Dependency manager deletes Amplitude AARs

### ISSUE THREAD

**Issue by indiecore** [amplitude/unity-plugin#38]
I'm using Amplitude in conjunction with other plugins that use the google external dependency manager and every time I resolve all the amplitude aars and jars are deleted.

The facebook AARs in the same directory are not deleted leading me to suspect something is up with the AARs from amplitude itself.

**Comment by haoliu-amp** [comment]
I guess you're using google resolver yourself too, right? That way, jars amplitude uses will be deleted. Please take a look at README, and we have a solution for it.

**Comment by indiecore** [comment]
Any reason these aren't included in the main download? The use of the dependency resolver is getting more and more common, including an AmplitudeDependencies.xml would probably make sense.

**Comment by haoliu-amp** [comment]
@indiecore Probably good to consider. Might do it later! Thanks!
