### ISSUE TITLE
Compatibility with Google Dependency Resolver

### ISSUE THREAD

**Issue by felipefujioka** [amplitude/unity-plugin#47]
As described in the [unity plugin integration guide](https://developers.amplitude.com/docs/unity#6-android-what-if-youre-also-using-unity-jar-resolver), in section 6 there is a known issue that causes aar and jar files associated with Amplitude to be removed from the unity project. The troubleshoot does not seem to work properly as adding a Dependency.xml file describing the android packages does not change the Resolver behavior.

Unity version: 2018.4.18f
Google Dependency Resolver version: 1.2.153
Amplitude SDk version: 2.27.0

**Comment by haoliu-amp** [comment]
Hello, could you tell me what steps do you do when you're doing integration? And what errors you're seeing?

**Comment by haoliu-amp** [comment]
Also, thee Unity version our SDK is based on is: 2019.3.11f. Please try to update your Unity version too.

**Comment by felipefujioka** [comment]
Hi,

The steps we followed were:
* We imported the unitypackage from the Amplitude website;
![Screen Shot 2020-08-27 at 18 42 25](https://user-images.githubusercontent.com/3421923/91497994-58742800-e895-11ea-8870-a98f0da2f82a.png)
The only difference is that we imported it in the Package folder, and defined some assembly definitions to use its code as a separated module
* After running a force resolve command from the Google Dependency Resolver, these logs were prompted
![Screen Shot 2020-08-27 at 18 43 04](https://user-images.githubusercontent.com/3421923/91498114-96714c00-e895-11ea-84d0-14c76f14f5e5.png)
Indicating that the AmplitudeDependencies.xml file was taken into consideration by the resolver.
* The resolution succeeds and ads the implementation entries in the mainTemplate.gradle file
![Screen Shot 2020-08-27 at 18 48 24](https://user-images.githubusercontent.com/3421923/91498314-e8b26d00-e895-11ea-9dab-8daabfdca018.png)
* but all AAR and Jar files are removed from the Plugins/Android folder
![Screen Shot 2020-08-27 at 18 49 33](https://user-images.githubusercontent.com/3421923/91498401-113a6700-e896-11ea-8eec-d777e5518a3d.png)
The Android folder is deleted too;

The Unity version is kinda of mandatory right now, as the update to the 2019 version would be pretty expensive for the whole project.

**Comment by haoliu-amp** [comment]
Thanks for sharing. How's your XXXDependencies.xml look like?

**Comment by felipefujioka** [comment]
I created a Dependencies.xml file in Assets/Editor/Dependencies.xml, it looks like this.

````
<dependencies>
  <androidPackages>
    <repositories>
      <repository>https://repo.maven.apache.org/maven2</repository>
    </repositories>

    <androidPackage spec="com.amplitude:android-sdk:2.27.0">
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>

    <androidPackage spec="com.squareup.okhttp3:okhttp:4.2.2">
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>

  </iosPods>
</dependencies>
````

**Comment by haoliu-amp** [comment]
Everything look alright. It should be there're some task which will clean up all the libraries in your project. Does your project depend on any other dependency management tool?

**Comment by felipefujioka** [comment]
We use Google Depency Resolver and Unity Package Manager. There are other third-party libraries that import AAR and JAR files that work just fine. I really can't find a reason why Amplitude's binaries would be removed like this. I will start a clean example project to see if it happens without other tools.

**Comment by felipefujioka** [comment]
Is there any architecture limitation in the aar targets?

**Comment by felipefujioka** [comment]
Just found out the error.

"Some users use unity-jar-resolver themselves. When they force resolve dependencies, it will clean up Amplitude related jars. For this case, what you would need to do is to declare those dependencies in your ***Dependency.xml file**."

In the integration guide that we followed in our first attempt indicated that the dependency file should be *Dependency.xml not *Dependencies.xml and that caused the confusion. The aar are not imported in the project and that is fine, because we are using a gradle build, and gradle will take care of the dependencies on the build process.

It might be good to fix the text in the integration guide though. 

Thanks for the support!

**Comment by haoliu-amp** [comment]
Glad you figured it out. However I wonder why it's *Dependency.xml for your case, since even google official doc said it's *Dependencies.xml

https://github.com/googlesamples/unity-jar-resolver

**Comment by felipefujioka** [comment]
It is wrong on amplitude unity integration guide actually.

![Screen Shot 2020-08-28 at 18 37 59](https://user-images.githubusercontent.com/3421923/91617145-b9ffc980-e95d-11ea-9e0f-ead6c7ca87ba.png)

**Comment by haoliu-amp** [comment]
@felipefujioka Oh! Thank you for catching it! We've fixed it.
