### ISSUE TITLE
Amplitude native dependencies

### ISSUE THREAD

**Issue by MartinGonzalez** [amplitude/unity-plugin#49]
This is more like a question to see if I'm not mistaken.

When I did import the latest amplitude .unitypackage (still waiting the UPM package) I see this tree of files

![image](https://user-images.githubusercontent.com/4130008/98565407-5a426a80-228c-11eb-97a4-0c02a7392808.png)

And I see that it has an AmplitudeDependencies.xml that is the file used by EDM4U to resolve native dependencies but it only has com.amplitude:android-sdk:2.28.2 and okhttp.

Why are they in Plugins/Android also?
Why jetbrains annotation and kotlin lib are not in the xml too? 
Is this because retrocompatibility?

Could this bring duplicated classes errors?

Thanks for the time! :D

**Comment by haoliu-amp** [comment]
@MartinGonzalez  jetbrains is used by okhttp library, that's why they're there.

**Comment by MartinGonzalez** [comment]
Just to know

Why you are delivering jar files if we can now have the EDM4U dependency to resolve them?

**Comment by Deroido** [comment]
I'm sorry.
Does Amplitude have any dependencies with com.android.installreferrer:installreferrer:1.0 ?

**Comment by Deroido** [comment]
I'm sorry.
Does Amplitude have any dependencies with com.android.installreferrer:installreferrer:1.0 ?

**Comment by MartinGonzalez** [comment]
@Deroido I think not, you can validate in Plugins/Android folder and also in AmplitudeDependencies.xml

```xml
 <androidPackage spec="com.amplitude:android-sdk:2.28.2">
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>

    <androidPackage spec="com.squareup.okhttp3:okhttp:4.2.2">
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
```

**Comment by dantetam** [comment]
Hello @MartinGonzalez ,

I can confirm your test is correct, the EDM4U plugin does replace old imported files with new ones.

Our engineering team has noticed it is inconvenient for SDK users to import the files themselves. It's one less engineering task and even internally we have run into import issues relating to Java version 8 vs 11 and the OpenJDK path used on MacOS and Windows.

Dante
