### ISSUE TITLE
Amplitude on WebGL

### ISSUE THREAD

**Issue by bassamseif** [amplitude/unity-plugin#51]
hi, thanks for creating this Unity plugin!

Will this work on a WebGL version of my Unity project or is it only targeting iOS & Android?

**Comment by dantetam** [comment]
Hello @bassamseif ,

Sorry for not getting back to you timely. 

Yes, we are only targeting iOS and Android. [This 2015 report from Unity](https://unity3d.com/sites/default/files/pr_downloads/bythenumbersunitytechnologies.pdf) writes that 91% of Unity installs are done on these two mobile platforms. We are also willing to discuss expansion of the Unity SDK to desktop apps when the business need arises.

(This paragraph below is my own personal opinion.)
I am actually a huge fan of WebGL technologies and believe they are the future. I am surprised there are not more desktop installs. The popular 4x fantasy strategy game Endless Legend developed through Unity desktop.

Thanks,
Dante
