### ISSUE TITLE
Amplitude Coppa/IDFA issue (AMPDeviceInfo)

### ISSUE THREAD

**Issue by Onbeygir** [amplitude/unity-plugin#52]
The update of our kids game got rejected by Apple. We've fixed IDFA related issues by running egrep -in ASIdentifierManager|AdSupport.framework|advertisingIdentifier|isAdvertisingTrackingEnabled, however, there seems to be one remaining culprit. 

2301:0x00010740	0x00000008	[ 18] _UnityAdvertisingIdentifier
227822:0x01E67312	0x00000014	[359] literal string: ASIdentifierManager
227824:0x01E67334	0x00000016	[359] literal string: advertisingIdentifier
229590:0x01E76331	0x0000007E	[431] literal string: The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at http://goo.gl/9vSsPb

[359] /Users/.../UnityFramework.build/Objects-normal/arm64/AMPDeviceInfo.o

We've enabled Coppa for Amplitude in code. This issue seems to be fixed in Amplitude-iOS v7.0.0 (https://github.com/amplitude/Amplitude-iOS/issues/296) but not fixed in the Unity package.

This issue currently blocks us from updating our game. Is there a workaround to fix it manually? Any ETA on fix? Or are we forced to remove amplitude completely,then if/when it's fixed, reenable it?

**Comment by haoliu-amp** [comment]
Thanks for reporting it. We will target to it updated by the end of next week.

**Comment by haoliu-amp** [comment]
Please try v2.0.0. We've taken idfa fetching out.
