### ISSUE TITLE
iOS14 support

### ISSUE THREAD

**Issue by SeriouslySam** [amplitude/unity-plugin#53]
## Summary

iOS14 support from the Amplitude iOS plugin should be brought over to Unity SDK.

## Motivations

As you probably know, Apple will start enforcing its new iOS14 IDFA collection rules early this year.

I’m seeing that Amplitude has a good support for this in their iOS SDK: https://github.com/amplitude/Amplitude-iOS/blob/master/CHANGELOG.md

But we’re using Unity for development and Amplitude’s Unity SDK hasn’t got any of these changes yet: https://github.com/amplitude/unity-plugin/blob/master/CHANGELOG.md
iOS release notes say that some users have got their apps rejected because of this (“Users reported that IDFA MACRO still do not prevent app rejections."), so it’s a high priority for us to get it updated.

Can you please advise us if there’s Unity SDK update planned from Amplitude’s side soon or how should we approach this issue?

**Comment by haoliu-amp** [comment]
Sorry for the wait. Please try v2.0.0. We've taken idfa fetching out.
