### ISSUE TITLE
Older .jar in the packaged .unitypackage

### ISSUE THREAD

**Issue by shilp-gupta** [amplitude/unity-plugin#6]
I notice that the repo contains amplitude Android plugin contains the amplitude-unity-2.6.0.jar whereas the github repo contains the amplitude-unity-2.9.2.jar. Is .unitypackage up to date?

**Comment by djih** [comment]
Where are you seeing amplitude-unity-2.6.0? I'm seeing the latest one in `Assets/Plugins/Android`. Also since we just released v2.10.0 of the Android SDK, I'm bumping 2.9.2 to 2.10.0
