### ISSUE TITLE
IDFA is null despite accepting prompt

### ISSUE THREAD

**Issue by MartinGonzalez** [amplitude/unity-plugin#65]
Unity: 2018.4.16 - 2019.4.16
Amplitude SDK: 2.1.0
Platform: Android & iOS

Hi!
I'm testing idfa behaviour, to receive or not receive it in amplitude events based on user answer in the Tracking prompt. Despite of allowing trackign amplitude is sending null as idfa value

![image](https://user-images.githubusercontent.com/4130008/111989525-a7fb9900-8af0-11eb-989f-de3c2051d11e.png)

Is there any consideration to have? Am I missing something?

Thanks

EDIT: We are not using Amplitude custom solution from [this page](https://developers.amplitude.com/docs/unity-ios-idfa-and-gps-setup). 
We have our own implementation to prompt the tracking permission

I leave some other questions

Why there is no method like setIdfa(string)
How should I call it if I have another implementation of how I use the prompt?
What is the instance name I should pass to setIdfaBlock?

And seems not to work the CUstomIDFA.m

![image](https://user-images.githubusercontent.com/4130008/111996209-89010500-8af8-11eb-999a-9bba34fd5d97.png)

**Comment by MartinGonzalez** [comment]
After testing more, setIdfaBlockInternal is being called, but idfa still null in events properties.

**Comment by MartinGonzalez** [comment]
After keep testing the issue was the instanceName. Since we do not name any instance by default I guess is "$default_instance".
It would be better in doc to be more clear in this part, perhaps say that is not mandatory to send an instance name or create an overload.
There are two ways to fix this
* Call `[[Amplitude instance] setAdSupportBlock:adSupportBlock];`
* Call `    [[Amplitude instanceWithName:anEmptyString] setAdSupportBlock:adSupportBlock];`

**Comment by dantetam** [comment]
Hello @MartinGonzalez,
Thank you for the deep dive into our code. If you are using your own custom implementation, how are you integrating this into Amplitude SDK?

There is no method `setIdfa(String)` because of internal engineering considerations. I assume your custom solution will be in Objective C. Feel free to overwrite the code in `setIdfaBlock(...)` with your own code. 

Thank you for your insight on the docs and I will go update that right now. If the instance name was the problem, were you able to set IDFA correctly?

Dante

**Comment by MartinGonzalez** [comment]
I share the actual working code

CustomIDFA.m
```
void setIdfaBlockInternalWith(const char* instanceName) {
    AMPAdSupportBlock adSupportBlock = ^{
        NSUUID *idfaUUID = [[ASIdentifierManager sharedManager] advertisingIdentifier];
        NSString *idfaString = [idfaUUID UUIDString];
        return idfaString;
    };
    
    NSString* string = [NSString stringWithFormat:@"%s" , instanceName];
    
    [[Amplitude instanceWithName:string] setAdSupportBlock:adSupportBlock];
}

void setIdfaBlockInternal(){
    setIdfaBlockInternalWith("");
}
```

CSharp
```
#if (UNITY_IPHONE || UNITY_TVOS)
    [DllImport ("__Internal")]
    private static extern void setIdfaBlockInternal();
#endif

void Start(){
#if (UNITY_IPHONE || UNITY_TVOS)
        setIdfaBlockInternal();
#endif
}
```

**Comment by dantetam** [comment]
This is a good improvement because it's consistent with the rest of the Unity API and other APIs. We have `Amplitude.getInstance()` and `Amplitude.`Just to be clear, the instanceName is an important parameter because it allows users to quickly "switch" between different settings.

**Comment by MartinGonzalez** [comment]
Also I'm testing that you need to call this setIdfaBlockInternal() after initializing Amplitude, instead the block will not work and will send the idfa as null even accepted

**Comment by dantetam** [comment]
Just to clarify: I have updated the documentation. I will update the code to allow the function call `setIdfaBlock()` (no arguments) as an improvement.

**Comment by haoliu-amp** [comment]
@dantetam Can we close this?

**Comment by dantetam** [comment]
@haoliu-amp This is just a small feature improvement for Unity. What should I do?
