### ISSUE TITLE
UPM Install: Editor.asmdef conflicts with com.unity.purchasing Editor.dll

### ISSUE THREAD

**Issue by fahall** [amplitude/unity-plugin#66]
## Expected Behavior

Installing Amplitude via UPM should not cause compilation errors.

## Current Behavior

After installing Amplitude via https://github.com/amplitude/unity-plugin.git?path=/Assets (on 3/23/2021), I see the following compilation error:

Plugin 'Assets/Plugins/UnityPurchasing/Bin/Editor.dll' has the same filename as Assembly Definition File 'Packages/com.amplitude.unityplugin/Editor/Editor.asmdef'. Rename the assemblies to avoid hard to diagnose issues and crashes.

## Possible Solution

Perhaps the Editor code could be optional? 

## Steps to Reproduce
 

1. Create Unity Project
2. Install com.unity.purchasing
3. Install Amplitude via UPM at url: https://github.com/amplitude/unity-plugin.git?path=/Assets
4. Check console for compilation errors (seen on iOS and Android build platforms)

## Environment
- Unity Plugin Version: Latest from Github as of 3/23/2021. Unclear what "version" that is. 
- Device: In Editor targeting iOS or Android (other platforms untested)
- Device OS and Version:  Unity 2020.3.0f1 on Windows 10 Pro 20H2

**Comment by dantetam** [comment]
Hello @fahall ,

I'll take a look into this. Thank you for the detailed context and steps to reproduce this bug. 

It looks like this step `Install com.unity.purchasing` causes an issue where our Amplitude SDK Editor asmdef (assembly definition file bundled with the plugin) conflicts with another plugin.

Dante

**Comment by fahall** [comment]
Yeah, it does seem to be a conflict between the two. 

I just installed the unitypackage from the most recent release in Github. Seems to be working so far 🤞 . If so, that would at least help narrow down when the conflict was introduced.

**Comment by dantetam** [comment]
Our download through UPM feature is actually very recent, only built a week ago. We only have one UPM config so we know where the issue resides.

I thought files in any folder named `Editor` requires an editor specific .asmdef file. Of course, these .asmdef files can collide often. Unity architecture is weirdly not so stable in this way.

**Comment by dantetam** [comment]
Tested the Amplitude SDK with the package `com.unity.purchasing` on both Android and iOS.

**Comment by fahall** [comment]
Great, thanks!

I like the encapsulation provided by asmdefs, but Unity’s decision to combine them with magic folders makes things tricky.

I’m glad we got this resolved so quickly!
