### ISSUE TITLE
Build Error with CustomIdfa.m

### ISSUE THREAD

**Issue by Gamenator** [amplitude/unity-plugin#71]
I get an error on Unity Cloud Build since I have used these instructions to have access to IDFA: https://developers.amplitude.com/docs/unity-ios-idfa-and-gps-setup

`Error: ../Libraries/Plugins/iOS/Amplitude/CustomIdfa.m:18:34: implicit conversion of 'int' to 'NSString * _Nullable' is disallowed with ARC`

I hope you can help me. Thanks.

**Comment by dantetam** [comment]
Hello @Gamenator ,

Thanks for reporting. Could you provide the `instanceName` you are calling the function `void setIdfaBlock(const char* instanceName) {...}` with?

Dante

**Comment by dantetam** [comment]
And where is the error reported? On generated xcode unity game?

**Comment by Gamenator** [comment]
I tried two variants: 
`setIdfaBlock (null)`and `setIdfaBlock (string.Empty)`. Because we do not set another instance name in our project. 
Yes, on generated xcode. 
Thanks for reply!

**Comment by Gamenator** [comment]
Thanks! I will try and give you a feedback.

**Comment by dantetam** [comment]
@Gamenator It's currently on the branch idfa2, so the unity package manager link would be

`https://github.com/amplitude/unity-plugin.git?path=/Assets#idfa2`

So try the code there, thanks.

**Comment by dantetam** [comment]
Oh wow, cool, thanks for testing as well @Gamenator . Good reporting and also @MartinGonzalez sorry for leaving this in the backlog for a while
