### ISSUE TITLE
Change meta file format from binary to text

### ISSUE THREAD

**Issue by keerthik** [amplitude/unity-plugin#82]
Unity `.meta` files can be binary or text, without change in functionality in the engine. 

The text format transmits via git and keeps track of change history in a human-readable way, which is very useful for a public repository.

**Comment by dantetam** [comment]
Hello @keerthik ,

Thank you for the observation. Did you by chance know how to do this? Is it a Unity setting unique to each developer working on the SDK? Is it a project setting?

**Comment by keerthik** [comment]
It is a per-project setting where you set `Project Settings/Editor/Asset Serialization` to `Force Text`. Doing this in the Unity Package Manager sample project that directly imports the root amplitude source files should make meta files and other Unity asset files (scenes, prefabs, presets, settings files, etc) human-readable with git-friendly diffsets from that point forward.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/203238/129831543-5dc6d2d2-d628-4cc5-a89a-95319d627254.png">

**Comment by dantetam** [comment]
Hello @keerthik , I tried this out. I only saw the .asset files change their binary. The .meta files stayed the same

**Comment by keerthik** [comment]
Can you confirm the project is set up to have Visible meta files?

<img width="516" alt="image" src="https://user-images.githubusercontent.com/203238/131398894-e424b434-e790-47c6-8bd2-5c604943b43d.png">

I am not sure if Unity has changed its implementation to only affect **new** files.

[This Unity Answers](https://answers.unity.com/questions/675704/how-to-re-serialize-assets-so-they-are-stored-as-t.html) thread suggests that toggling to Force Binary and back to Force Text will convert all files.

If that doesn't work, you may need to delete the meta files and allow Unity to re-create them by re-loading the scene with the editor open. If I get time by this weekend I can use the latest commit from `main` and see if I can submit a pull request.

**Comment by keerthik** [comment]
It looks like `main` now uses text-based `.meta` files, so seems you folks managed to work that into one of the recent versions. It merged fine with my fork, so I'm closing this issue. 

Thanks!
