### ISSUE TITLE
Android SDK Version Update Request (v2.31.4)

### ISSUE THREAD

**Issue by jmozgawa** [amplitude/unity-plugin#87]
## Summary

Hi, I've notice that in versions (v2.31.4) you've fixed/handled cursor exceptions, which is exactly what I need for my apps cause I'm getting a lot of crashes relating to that issue.

Would you be so kind and release new Unity-SDK with updated Android Package to v2.31.4 or at leas tell me when would you do so ?

Otherwise it would be pretty inconvenient to replace it manually  because I've already imported Unity SDK with use of Unity package manager and the stuff under 'Packages' folder is rather immutable.

Thank you in advance.

**Comment by dantetam** [comment]
Hello @jmozgawa ,

That's a really good callout. We've created a ticket for that and will update this soon (within a week). 

Dante

**Comment by jmozgawa** [comment]
That's good news. Thank you soo much ;)

**Comment by dantetam** [comment]
I'll keep this open to remind our team of the issue. And thank you again so much for reporting.

**Comment by dantetam** [comment]
For posterity, fixed in 2.2.2
