### ISSUE TITLE
Warning when using plugin

### ISSUE THREAD

**Issue by StephenHodgson** [amplitude/unity-plugin#99]
## Expected Behavior

No errors or warnings when using plugin

## Current Behavior

```
Assembly for Assembly Definition File 'Packages/com.amplitude.unityplugin/Plugins/AmplitudeSDKPlugins.asmdef' will not be compiled, because it has no scripts associated with it.
```

## Possible Solution

remove assembly definition in plugins folder

**Comment by dnshi** [comment]
Thanks for reporting the issue. The most recent release does not include any `. asmdef` file. Feel free to update the Amplitude Unity plugin. Thanks.
